eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
server:
  port: 1111  #6å¼€å§‹ç«¯å£æ— æ³•ä½¿ç”¨ ğŸ˜³ å¾…è§£
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-ribbon:
      path: /api-ribbon/**
      serviceId: service-ribbon   #/service-ribbon/** è·¯å¾„ä¹Ÿå¯ä»¥è®¿é—®åˆ°

    api-feign:
      path: /api-feign/**
      serviceId: service-feign

    api-vhr:
      path: /api-vhr/**
      serviceId: hr
